


insert into Sponsor (nome,nazione,ambito,societa) VALUES
("Runte, Brown and Langworth","Germany","B2C monetize supply-chains","Dickens - Reinger Group"),
("Crist, Lindgren and Predovic","Faroe Islands","e-business whiteboard e-commerce","Flatley, Mitchell and Schamberger Group"),
("Feest and Sons","Bangladesh","one-to-one reinvent infomediaries","Marquardt - Thompson Group"),
("Kohler - Robel","Nigeria","bricks-and-clicks innovate communities","Jacobson, Kautzer and Kling Inc"),
("Grant LLC","New Zealand","cross-media e-enable e-tailers","Zieme - Farrell LLC"),
("O'Hara, Zemlak and Boehm","Turkmenistan","sexy matrix ROI","Aufderhar, Hamill and Zieme Inc"),
("Roob - Casper","Kenya","value-added productize technologies","Brown, Heathcote and Kilback and Sons"),
("Emard Group","Saint Helena","compelling benchmark platforms","Skiles - Kulas and Sons"),
("Wilkinson LLC","Grenada","e-business transition relationships","Fritsch LLC Inc"),
("Kshlerin, Mueller and Wilkinson","Falkland Islands (Malvinas)","leading-edge extend communities","Langworth Group and Sons"),
("Walsh Group","French Polynesia","e-business cultivate models","Schuppe - Tillman Inc"),
("Mueller Group","Tajikistan","magnetic evolve functionalities","Denesik - Kshlerin LLC"),
("Nicolas - Hand","Taiwan","leading-edge iterate initiatives","Bechtelar - Streich and Sons"),
("Pfannerstill Group","United States of America","customized evolve technologies","Jast Inc and Sons"),
("Gulgowski, Mertz and Kertzmann","Dominican Republic","front-end repurpose interfaces","Breitenberg LLC LLC"),
("Mraz - Breitenberg","New Caledonia","frictionless unleash infrastructures","Ondricka, Hickle and Tremblay Group"),
("Kuvalis - Schulist","Grenada","leading-edge seize architectures","Schimmel - Raynor Group"),
("McKenzie, Bergstrom and Berge","Tajikistan","vertical benchmark channels","Gutmann - Nikolaus and Sons"),
("Lehner Group","Libyan Arab Jamahiriya","sticky seize initiatives","Ernser Group and Sons"),
("Wisozk, Bernier and Schowalter","Maldives","intuitive architect platforms","Abbott, Sipes and Abernathy Inc"),
("Flatley - Ledner","Wallis and Futuna","viral iterate synergies","Emmerich - Upton Group"),
("Willms - Gutkowski","Cote d'Ivoire","B2B mesh convergence","Hamill, Gusikowski and Anderson and Sons"),
("Hessel and Sons","Northern Mariana Islands","bricks-and-clicks disintermediate content","D'Amore LLC LLC"),
("Schiller - Leuschke","Ireland","web-enabled scale networks","Hahn, Cronin and Pollich and Sons"),
("Dibbert and Sons","Denmark","plug-and-play incubate methodologies","Lueilwitz, Schmitt and Wintheiser LLC"),
("Abbott - Wunsch","Zimbabwe","real-time engineer e-commerce","Leannon Inc Group"),
("Dickens, McGlynn and Denesik","Saint Pierre and Miquelon","vertical redefine web-readiness","Batz LLC and Sons"),
("Schinner Inc","Spain","turn-key drive partnerships","Yundt - Mann and Sons"),
("Pouros - Champlin","Costa Rica","magnetic reintermediate experiences","Conroy, Okuneva and Casper LLC"),
("Schmidt - Hamill","Macedonia","end-to-end engineer interfaces","Yundt, Schneider and Hamill Group"),
("Kohler and Sons","Austria","efficient engage content","Von - Grant and Sons"),
("Rosenbaum, Schinner and Bednar","Cambodia","killer morph applications","Hermann and Sons and Sons"),
("Goyette Group","Mauritania","best-of-breed orchestrate e-business","Auer Group Group"),
("Ferry - Mitchell","Senegal","cross-media strategize action-items","Zieme, Kertzmann and Moen Inc"),
("Renner, Pouros and Gleichner","Qatar","real-time recontextualize ROI","Smith LLC Inc"),
("Kuhic - Ullrich","Turkey","sticky grow applications","Parisian, Murazik and Corkery Inc"),
("Cummings, Gleason and Weimann","Cuba","efficient productize ROI","Powlowski, Parisian and Boyle Inc"),
("Crona - Wisoky","Oman","best-of-breed maximize solutions","Kozey, Shanahan and Wolf Group"),
("MacGyver and Sons","Canada","value-added morph models","Fahey and Sons Inc"),
("O'Kon Inc","San Marino","B2C brand convergence","Smith - Steuber Group"),
("Ritchie and Sons","Ukraine","transparent enhance metrics","Kunde - Kuhn Group"),
("Cassin, Hermann and Turcotte","Kiribati","killer enhance experiences","Predovic LLC Group"),
("Stanton, Goldner and Walker","Mauritania","one-to-one empower methodologies","Rath - Mayer LLC"),
("Towne and Sons","Spain","scalable morph partnerships","Veum LLC Group"),
("Hauck Inc","Monaco","enterprise transition infrastructures","Macejkovic, Mertz and Stamm Group"),
("MacGyver, Reichert and Hartmann","Bosnia and Herzegovina","dynamic benchmark niches","Boehm, Rau and Cole LLC"),
("Collins, Bernier and Langworth","Sudan","magnetic enable e-tailers","Eichmann and Sons Inc"),
("Beier Inc","Burkina Faso","24/7 engineer platforms","Marquardt and Sons LLC"),
("Nicolas, Schumm and Becker","Grenada","bricks-and-clicks exploit technologies","O'Keefe LLC Group"),
("Greenholt Group","Turks and Caicos Islands","B2C drive methodologies","Pouros Inc Group"),
("Goyette, Marvin and Glover","Guatemala","clicks-and-mortar seize architectures","Sawayn - Grady Inc"),
("Toy LLC","Macao","dynamic mesh e-services","Kuhlman Inc Inc"),
("Ratke, Robel and Ryan","Seychelles","strategic iterate initiatives","Cruickshank and Sons and Sons"),
("Conroy, Oberbrunner and Kuhn","Kiribati","one-to-one engineer bandwidth","Ritchie, Blanda and Ratke Inc"),
("Robel Group","Armenia","best-of-breed syndicate experiences","Jones, Swift and Kuhic Group"),
("Feest, Boyer and Mosciski","Democratic People's Republic of Korea","visionary harness infrastructures","Macejkovic and Sons and Sons"),
("Keeling Group","Equatorial Guinea","robust enable architectures","Kub, Lesch and O'Keefe Group"),
("Mante - Fritsch","Tuvalu","dynamic seize e-tailers","Orn, Hartmann and Kuhn LLC"),
("Pacocha Group","Finland","24/7 orchestrate deliverables","Veum - Pouros Inc"),
("Grady Group","Syrian Arab Republic","clicks-and-mortar productize infrastructures","Denesik, Blanda and Parker Inc"),
("Rowe Inc","Angola","one-to-one deliver metrics","VonRueden Inc and Sons"),
("Miller Group","Argentina","vertical transition markets","Torp and Sons LLC"),
("Wolff LLC","Kiribati","out-of-the-box incubate models","Johnson Inc Group"),
("Ortiz, Wunsch and Wisoky","Lithuania","value-added cultivate e-services","Ledner - Roob LLC"),
("Tillman, Herzog and Weber","Sri Lanka","out-of-the-box scale infomediaries","Olson Inc and Sons"),
("Zulauf - Leuschke","Malaysia","global monetize portals","Gutmann, Conroy and Brekke Group"),
("Bahringer Inc","Wallis and Futuna","world-class facilitate models","Bergnaum - Halvorson Group"),
("Stoltenberg Group","Peru","holistic streamline partnerships","Feil - Berge LLC"),
("Satterfield, Berge and Rice","Haiti","real-time transform e-services","Pagac LLC and Sons"),
("Barton, Jacobs and Abernathy","Grenada","vertical enable communities","Senger LLC Inc"),
("Casper LLC","Mexico","customized streamline functionalities","Schmitt, Hegmann and Hackett and Sons"),
("Reichel - Feil","Central African Republic","killer productize platforms","Schinner, Hansen and Wunsch LLC"),
("Boyer - Schumm","Cape Verde","seamless architect methodologies","Schimmel, Rempel and Corkery and Sons"),
("Douglas - Brown","Marshall Islands","ubiquitous incubate partnerships","Gutkowski Group Inc"),
("Hammes - Quigley","Guinea","impactful benchmark portals","Schaden - Blanda Group"),
("Maggio, Mertz and Bogan","Sierra Leone","best-of-breed implement web-readiness","Bergnaum, Kemmer and Kutch LLC"),
("Koelpin - O'Reilly","Virgin Islands, U.S.","turn-key visualize mindshare","Ferry - Thiel LLC"),
("McCullough, Fritsch and Littel","United States of America","out-of-the-box target channels","Koepp, Kihn and Wilderman Group"),
("Wolff - Kulas","Senegal","visionary implement e-markets","Dach Inc LLC"),
("Turner, Moen and Treutel","Bolivia","collaborative productize channels","Barton, Balistreri and Stanton and Sons"),
("Bogan - Kerluke","Niger","robust generate technologies","Blanda Inc Inc"),
("Hessel - Ward","Gabon","revolutionary enable networks","Stracke and Sons Group"),
("Mosciski Group","Micronesia","front-end exploit solutions","Hirthe - Haag LLC"),
("Rath LLC","Belgium","global innovate supply-chains","Schmidt - Simonis and Sons"),
("O'Kon - Wiegand","Papua New Guinea","vertical embrace mindshare","Hills LLC LLC"),
("Stoltenberg - Funk","Sao Tome and Principe","viral utilize channels","Ruecker - Hilpert Group"),
("Jenkins, Pacocha and Pouros","Oman","24/365 matrix eyeballs","Koss - Becker and Sons"),
("Emmerich, Cassin and Stoltenberg","Macedonia","viral reinvent portals","Hansen LLC LLC"),
("Crooks, Orn and McDermott","Uzbekistan","value-added mesh content","Harris LLC Inc"),
("Barrows Inc","Netherlands","cutting-edge syndicate experiences","Volkman, Schultz and Brown and Sons"),
("Schuster, Towne and Crona","Mayotte","mission-critical matrix communities","Effertz and Sons and Sons"),
("Beatty, Weimann and Heaney","Moldova","virtual generate technologies","Mayer, Schiller and Howell Inc"),
("Goyette Group","Zimbabwe","extensible syndicate e-markets","Little LLC LLC"),
("McGlynn LLC","American Samoa","frictionless grow architectures","Mraz, Bayer and Hirthe and Sons"),
("Marks and Sons","Libyan Arab Jamahiriya","front-end deliver networks","Hessel LLC Inc"),
("Pacocha, Parisian and Heller","Indonesia","distributed expedite deliverables","Corkery - Lind Group"),
("Considine LLC","Poland","innovative embrace infrastructures","Wilkinson LLC LLC"),
("Howell Inc","Canada","B2C monetize niches","Russel, Mitchell and Ledner Group"),
("Veum, Sawayn and Mayer","Montserrat","user-centric redefine e-business","Armstrong Inc Inc"),
("Wilderman Group","Guyana","visionary incubate experiences","Murazik - Renner and Sons"),
